# If you come from bash you might have to change your $PATH.
#export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
ZSH=/usr/share/oh-my-zsh/

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="sammy"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)


# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh


## user define
# aliases
alias pacclean="paccache -r && paccache -ruk0 && pacman -Qdt"
alias radio="mpv --profile=radio"
alias sproc="ps -aux|grep -v "grep"|grep -i --color"
alias paccheck="checkupdates; auracle sync"
alias pacupdate="sudo pacman -Syu"
alias vimenc='vim -c '\''let $enc = &fileencoding | execute "!echo Encoding:  $enc" | q'\'''
alias torim="torify mpv --ytdl-raw-options=ignore-config="
alias toriy="torify youtube-dl --ignore-config -o /mnt/dAta/.temp/hub/'%(title)s.%(ext)s'"
alias youtube-dl-ignore="youtube-dl --ignore-config -o /mnt/DumP/.temp/'%(title)s.%(ext)s'"
alias tempmon="watch -n 1 'sensors | egrep -i package\|fan1 && nvidia-smi -a|egrep -i current\ temp\|fan'"
alias jctlcheck="journalctl -b-0 | grep -i -v 'xylitol kernel: RAS: Correctable Errors collector initialized.\|xylitol tor\|xylitol kernel: nvidia: module verification failed: signature and/or required key missing - tainting kernel\|ACPI Warning: SystemIO range\|xylitol kernel: DMAR-IR: Queued invalidation will be enabled to support x2apic and Intr-remapping.\|xylitol kernel: ehci-pci 0000:00:1a.0: cache line size of 64 is not supported\|xylitol kernel: xhci_hcd 0000:00:14.0: cache line size of 64 is not supported\|xylitol kernel: ehci-pci 0000:00:1d.0: cache line size of 64 is not supported\|xylitol kernel: iTCO_wdt: unable to reset NO_REBOOT flag, device disabled by hardware/BIOS\|xylitol colord' | grep -i 'warn\|error\|fail\|critical\|fatal\|already\|??\|unable\|invalid\|not supported'"
#alias jctlcheck="journalctl -b-0 | grep -i 'warn\|error\|fail\|critical\|fatal\|already\|??\|unable\|invalid\|not supported'"
#alias jctlmon="journalctl -b-0 -f | grep -i -v 'kernel: RAS: Correctable Errors collector initialized.' | grep -i 'warn\|error\|fail\|critical\|fatal\|already\|??\|ignor'"
alias jctlmon="journalctl -b-0 -f | grep -i 'warn\|error\|fail\|critical\|fatal\|already\|??\|ignor'"
#alias mpv='/home/paseu/dotfiles/desktop/scripts/mpv_thumbnail --no-fs'
#alias prename='perl-rename'

# Persistent rehash
zstyle ':completion:*' rehash true
